### PR TITLE
Don't set read/write capacity in PAY_PER_REQUEST billing mode

### PR DESCRIPTION
**Pull request by alexjurkiewicz**
This causes errors at plan-time now:

```
Error: 2 errors occurred:
	* read_capacity can not be set when billing_mode is "PAY_PER_REQUEST"
	* write_capacity can not be set when billing_mode is "PAY_PER_REQUEST"

  with module.dynamodb_table.aws_dynamodb_table.default[0],
  on .terraform/modules/dynamodb_table/main.tf line 46, in resource "aws_dynamodb_table" "default":
  46: resource "aws_dynamodb_table" "default" {
```

### CODE REVIEW

**Review by Gowiem — DISMISSED** [review]
Easy -- Thanks as always @alexjurkiewicz 👍

**Comment by Gowiem** [comment]
@alexjurkiewicz our validate check got stuck. Mind pushing an empty commit to try and trigger it again?

**Comment by alexjurkiewicz** [comment]
done

**Review by Gowiem — APPROVED** [review]

**Comment by alexjurkiewicz** [comment]
thanks!

**Pull request merged**
