### PR TITLE
Add possibility to define custo kms key for server side encryption

### PR DESCRIPTION
**Pull request by dmitriy-lukyanchikov**
## what
* Add possibility to define custom kms key for server-side encryption

## why
* its useful when you want to create you on custom managed KMS key

### CODE REVIEW

**Comment by dmitriy-lukyanchikov** [comment]
looks like pipeline is broken

**Comment by aknysh** [comment]
@dmitriy-lukyanchikov thanks for the PR, LGTM.
Can you please run the following commands in the repo root:

```
make init
make github/init
make readme
```

It will add some new GitHub actions and workflows that we are adding to all repos.

Thanks

**Review by aknysh — COMMENTED** [review]
please see commants

**Comment by dmitriy-lukyanchikov** [comment]
@aknysh hello, looks like its failing anyway, dont know why

**Review by aknysh — APPROVED** [review]
thanks @dmitriy-lukyanchikov

**Pull request merged**
