### PR TITLE
update terraform-aws-dynamodb-autoscaler version

### PR DESCRIPTION
**Pull request by woz5999**
## what
set minimum versions for providers without pinning to a specific major version

## why
the current method makes it very difficult to maintain or upgrade consistent provider versions within a project

## references
https://www.terraform.io/docs/configuration/provider-requirements.html#best-practices-for-provider-versions

### CODE REVIEW

**Comment by woz5999** [comment]
unclear why this build is failing. seems unrelated to code changes.

**Comment by jurgenweber** [comment]
love your work @woz5999 , any chance this can get merged?

**Comment by woz5999** [comment]
@osterman

**Review by osterman — APPROVED** [review]

**Comment by woz5999** [comment]
@osterman @aknysh looks like this is ready to merge.

**Pull request merged**
